[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["cd backend && python3 -m pip install --user -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python3 -m gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120" 