[phases.setup]
nixPkgs = ["python311", "pip", "postgresql", "redis", "ca-certificates"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -c \"import certifi; print('CA Bundle path:', certifi.where())\"",
    "python -c \"import ssl; print('SSL version:', ssl.OPENSSL_VERSION)\"",
    "python -c \"from app.utils.ssl_config import configure_ssl; configure_ssl()\""
]

[start]
cmd = "cd backend && python3 wsgi.py"

[variables]
PYTHON_VERSION = "3.11"
FLASK_ENV = "production" 