"""add pixel_id to facebook_token

Revision ID: 1e6b6b6cd79d
Revises: 9fe2dfb8ed3f
Create Date: 2025-07-01 00:38:18.265846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6b6b6cd79d'
down_revision = '9fe2dfb8ed3f'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Sütunu nullable olarak ekle
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_id', sa.String(length=255), nullable=True))

    # 2. Eski kayıtlara default değer ata
    op.execute("UPDATE facebook_token SET pixel_id = 'default-pixel-id' WHERE pixel_id IS NULL")

    # 3. Sütunu NOT NULL yap
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.alter_column('pixel_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.drop_column('pixel_id')

    op.create_table('domain',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verification_token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
