"""add gtm_container_id to facebook_token

Revision ID: 9fe2dfb8ed3f
Revises: e2c29eb1a2df
Create Date: 2025-06-30 21:46:31.946797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe2dfb8ed3f'
down_revision = 'e2c29eb1a2df'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Sütunu nullable olarak ekle
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gtm_container_id', sa.String(length=255), nullable=True))

    # 2. Eski kayıtlara default değer ata
    op.execute("UPDATE facebook_token SET gtm_container_id = 'default-gtm-id' WHERE gtm_container_id IS NULL")

    # 3. Sütunu NOT NULL yap
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.alter_column('gtm_container_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_token', schema=None) as batch_op:
        batch_op.drop_column('gtm_container_id')

    # ### end Alembic commands ###
